### ISSUE TITLE
Kitten Death Loop after Reset

### ISSUE THREAD

**Issue by oliversalzburg** [kitten-science/kitten-scientists#105]
### Version Check

- [X] I have updated to `v2.0.0-beta.1` or later.
- [X] I have updated to the `nightly` build from last night (or latest one available).
- [X] I have tested with the latest source code from `main` as of today.

### What browser are you using?

Firefox

### Describe the Bug

In certain conditions, when the game is reset, all catnip will be spent right after the reset, then a kitten is assigned as woodcutter, leading to negative catnip production. Before another kitten can be assigned as farmer, the first one dies and the cycle repeats.

This is potentially related to:
- #15 
- #86

**Comment by acmihal** [comment]
In my fast paragon run settings I have the 'refine catnip into wood' workshop setting turned off, catnip fields are limited to 300, plus there are unmerged changes in my branch to change the village distribution algorithm to first cap priest and farmer before assigning to any other classes. This is part of the strategy to unlock SR as fast as possible. I think that it is coincidence that farmer appears before priest in the list of jobs that are considered for assignment, so it enters a farmer-priest-farmer-priest... loop with farmer first until both farmer and priest hit the cap. The farmer cap is 5 and priest is 10 in my fast paragon settings. This is probably not very robust.

**Comment by oliversalzburg** [comment]
Some very good points. Parts of this is just my configuration being bad, but the job assignment should at least assign the first kitten as farmer in any case and only assign other jobs if they can be sustained. That seems like a reasonable change to make.

**Comment by oliversalzburg** [comment]
After more research and more resets, I no longer feel like this is a bug. It's really mostly configuration and more complex logic to try to work around suboptimal settings, isn't in line with KS development goals anyway.
