### ISSUE TITLE
Settings Profile Management

### ISSUE THREAD

**Issue by oliversalzburg** [kitten-science/kitten-scientists#106]
### Describe the Feature

It should be possible to author, export, import, and switch between multiple (ideally, unlimited) settings profiles.

Settings profiles should be distinct from the "engine state snapshots" we use right now. They should be dramatically less verbose and represent a diff from a baseline settings profile. Ideally, the baseline is configurable as well.

Settings profiles must be stable and robust. Users who create KSv2 settings profiles, should have a guarantee that those profiles will load successfully and entirely in any future KSv2 version (v3 can introduce breaking changes).

It should be easy and comfortable to author new settings profiles both trough the KS UI, and through a text-driven approach outside of KG/KS.

It would be nice if we could load/reference remote content in settings profiles. Something like:
```yaml
profile:
  extends: https://raw.githubusercontent.com/kitten-science/kitten-scientists/main/baseline.yml
```

**Comment by petethered** [comment]
Ha... this would be interesting.

I currently turn things on/off at different stages of the game, so being able to setup a "Getting Started", "Building To Space", "Building Flux", "Time Skip to infinity" profiles would be interesting.

**Comment by oliversalzburg** [comment]
> I currently turn things on/off at different stages of the game, so being able to setup a "Getting Started", "Building To Space", "Building Flux", "Time Skip to infinity" profiles would be interesting.

In theory, you can also use settings snapshots for that right now, but not even I am doing that right now. It just doesn't feel very robust.
