### ISSUE TITLE
Fixing cryochambers is free

### ISSUE THREAD

**Issue by acmihal** [kitten-science/kitten-scientists#130]
### Version Check

- [X] I have updated to `v2.0.0-beta.4` or later.
- [X] I have updated to the `nightly` build from last night (or latest one available).
- [X] I have tested with the latest source code from `main` as of today.

### What browser are you using?

firefox

### Describe the Bug

The TimeManager.ts:fixCryochambers() calls doFixCryochamber, but the payPrice is only in buyItem, not in doFixCryochamber. Maybe there is another way to mock pushing the button?

**Comment by oliversalzburg** [comment]
Why don't we just call `buyItem` instead?

**Comment by acmihal** [comment]
buyItem requires model, event, callback params. Not sure what needs to go there. Haven't studied it enough.

**Comment by oliversalzburg** [comment]
`model` needs the button model, which we have. The other two can be ignored.
