### ISSUE TITLE
Add an option to prevent trading with Zebra if Titanium is full

### ISSUE THREAD

**Issue by OlivierGagnon** [kitten-science/kitten-scientists#131]
### Describe the Enhancement

Add an option to prevent trading with Zebra if Titanium is full

There would be a checkbox under Trading > Zebra, when enabled (maybe with a limit lightning), it would not trade with Zebras if your titanium is full, or nearly full.

Currently, it'll trade every tick, even if your titanium is full.

**Comment by oliversalzburg** [comment]
I assume there's still blueprints and other resources to be gained from the trade, that's likely why it would still happen so often, even when limited. Otherwise, this might be a bug.

In general, I feel like this would be too specific of a setting to have, that just opens the door for more exceptions to make to trading behavior. This is likely better suited to be solved by a future feature.

**Comment by acmihal** [comment]
I was just looking at this code in the context of blueprints from shark trades. If a trade has any output with limited capacity, and that output is already at or above capacity, then the entire trade is cancelled. The code path is the "Distribute max trades without starving any race" section, and then into getLowestTradeAmount, and then the loop that computes highestCapacity. It should return zero when any trade output is at capacity and the race should be spliced out of the array.  If either titanium or iron are full, there should be no zebra trades anymore. @OlivierGagnon if you can post a savegame I'd like to take a look.

**Comment by oliversalzburg** [comment]
If there is a real bug, it should be fixed, but from a feature perspective, we already have un/limited trading, and sometimes even that isn't enough options. If we want to go further, I feel like all the individual costs and results for a trade should be configurable individually for if they are to be taken into account. I don't like that level of complexity yet.

I am always open to expanding functionality that applies generically, but I don't like adding a singular option that just applies to Zebras and adds another exceptional behavior to the trading. The code is already probably way more complex that it needs to be.

**Comment by oliversalzburg** [comment]
Closing this for now, but always open for further discussion :)
