### ISSUE TITLE
Feature Request: Prioritize Solar Revolution

### ISSUE THREAD

**Issue by oliversalzburg** [kitten-science/kitten-scientists#14]
Original issue https://github.com/oliversalzburg/cbc-kitten-scientists/issues/125 by @Fhurries

> If sensible, would be interesting to see and test out an additional option for the script to save/reserve 500 gold for the unlock once it is purchasable (storage space, visible on religion screen) and to ignore other religion upgrades until then. Would work great with the gold saved from a chronosphere reset to speed up early game (instead of automation blowing it all on buildings).
> 
> Additionally, an adjustable parameter or tolerance for the time remaining to get the required gold would make this more accessible for those with 0 production bonuses and those in end-game. IE, a tolerance of 15 minutes means it will not attempt to save for the gold unless the time remaining to reach the 500 gold tech reaches 15 minutes or lower - this should make it so early run trading and buildings are not completely ignored even with the unlock available.

**Comment by acmihal** [comment]
I'd also like this feature for fast paragon runs. I think it would work if there was an option for the auto kitten assignment to fill up Priests to the specified max limit before any of the other roles. Enough gold and catnip are carried over by Chronospheres in the paragon farming cycle to not cause problems. You would set the max priests to hit a few seconds before getting to 750 faith.

**Comment by oliversalzburg** [comment]
Closing Kitten Engineer candidate tickets for the time being. See <https://kitten-science.com/engineers/> for details.
