### ISSUE TITLE
Automate smelter management to ensure positive resource flow (and turn off smelters when the output resource(s) are maxed)

### ISSUE THREAD

**Issue by dethmourne** [kitten-science/kitten-scientists#156]
### Describe the Feature

Smelters currently don't appear to have any mechanism by which Kitten Scientists can increment how many are in use, if any. Automation of this per the following rules would likely be a net benefit to the project:

1) Ensure positive input resource flow - that is, don't make wood/s or mineral/s go negative.

2) Enable as many smelters as possible, given 1.

3) If all currently created smelter resources are at full capacity (e.g. near the beginning it's easy to hit 300/300 iron and have naught to spend it on), turn off all smelters until those resources are spent or a new smelted resource appears that is not at capacity.

**Comment by dethmourne** [comment]
So, playing in Iron Will right now, it occurs to me it might be occasionally useful to be able to make inputs temporarily go to negative gain in order to generate iron - so a toggle for "accept resource losses for output gain" or some such might be worthwhile.

**Comment by oliversalzburg** [comment]
I'm not sure yet if this is something I would want to support in the core of KS. In general, I'm not a big fan of KS features that create exceptions in the behavior of the script. Those can create conflicting behavior with other automations, and can result in unpredictable outcome, or having to balance automations between each other.

There have been many feature requests like this, and I always felt these would fit better into a completely new userscript. This new userscript would work alongside KS and switch between different settings states, based on rules you can define yourself. However, the work on this userscript hasn't even started yet.

So, sorry, if this is disappointing, but I feel like work on this feature might have to be delayed quite a bit. Smelter optimization sounds interesting enough that I'll keep it on the beta release plan, but a solution is likely months away.

**Comment by dethmourne** [comment]
Perfectly reasonable.

**Comment by oliversalzburg** [comment]
I'm marking this as a Kitten Engineers candidate. Please see <https://kitten-science.com/engineers/> for more details.
