### ISSUE TITLE
Feature Request: Time Skip Ignore Overheat

### ISSUE THREAD

**Issue by acmihal** [kitten-science/kitten-scientists#18]
The Time Skip feature could have an Ignore Overheat option that will pay for the skip even if there is a TC penalty for going over the Chronoheat max.
I'm thinking of using this for fast paragon runs where you want to get to Redmoon as soon as Unob production comes online. It is cheaper to pay the penalty than to build furnaces. The run is going to auto reset before year 30 so the penalty is not going to get out of control in this scenario.

**Comment by oliversalzburg** [comment]
It sounds reasonable to add this. Nice idea

**Comment by acmihal** [comment]
Here is a workaround that will time skip ignoring overheat.
```diff
diff --git a/packages/userscript/source/TimeControlManager.ts b/packages/userscript/source/TimeControlManager.ts
index b1ca9e8..0c07c6d 100644
--- a/packages/userscript/source/TimeControlManager.ts
+++ b/packages/userscript/source/TimeControlManager.ts
@@ -374,7 +374,9 @@ export class TimeControlManager {
     const cyclesPerEra = this._host.gamePage.calendar.cyclesPerEra;
     const factor = this._host.gamePage.challenges.getChallenge("1000Years").researched ? 5 : 10;
     // How many times/years we can skip before we reach our max heat.
-    let canSkip = Math.min(Math.floor((heatMax - heatNow) / factor), this.settings.timeSkip.max);
+    // FIXME ACM skip even if overheat
+    //let canSkip = Math.min(Math.floor((heatMax - heatNow) / factor), this.settings.timeSkip.max);
+    let canSkip = this.settings.timeSkip.max;
     // The amount of skips to perform.
     let willSkip = 0;
     // If the cycle has more years remaining than we can even skip, skip all of them.
```

**Comment by oliversalzburg** [comment]
I feel like the changes in #68 should enable this behavior by setting the max to infinity. Please let me know if I'm mistaken :)

**Comment by oliversalzburg** [comment]
Yeah, that wasn't the fix. This will really need a dedicated setting.
