### ISSUE TITLE
"Fix Cryochamber" generates constant false log messages

### ISSUE THREAD

**Issue by ArcanErasmus** [kitten-science/kitten-scientists#185]
### Version Check

- [X] I have updated to `v2.0.0-beta.6` or later.
- [ ] I have updated to the `nightly` build from last night (or latest one available).
- [ ] I have tested with the latest source code from `main` as of today.

### What browser are you using?

Firefox, desktop, windows 10

### Describe the Bug

When "Fix Cryochamber" is enabled, it repeatedly generates a message claiming a cryochamber was fixed, even when there are not enough resources and no cryochambers were fixed.

### Your Savegame

[Kittens Game - Run 6 - Year 2165 - Summer, day 76.txt](https://github.com/kitten-science/kitten-scientists/files/10985402/Kittens.Game.-.Run.6.-.Year.2165.-.Summer.day.76.txt)

### To Reproduce

1. Have the button to fix cryochambers
2. Have cryochambers that need fixing, but not enough resources to do so
3. Enable "Fix Cryochamber" under "Time"
4. Observe the log

### Screenshots

![image](https://user-images.githubusercontent.com/8963206/225469559-60d50810-4856-447f-ac18-dc16c66afba1.png)

**Comment by oliversalzburg** [comment]
Should be fixed in next release. Thanks for reporting :)
