### ISSUE TITLE
Settings dont persist on alpha branch

### ISSUE THREAD

**Issue by dododome01** [kitten-science/kitten-scientists#191]
### Version Check

- [X] I have updated to `v2.0.0-beta.7` or later.
- [X] I have updated to the `nightly` build from last night (or latest one available).
- [ ] I have tested with the latest source code from `main` as of today.

### What browser are you using?

Firefox

### How are you loading Kitten Scientists?

Userscript Manager (Tampermonkey)

### Describe the Bug

Script settings dont persist through reloads on alpha branch.

### To Reproduce

1. Open alpha branch
2. Change some KS settings
3. Save
4. Reload

**Comment by oliversalzburg** [comment]
Thanks for updating 😀
