### ISSUE TITLE
Automated unicorn sacrifice cannot keep up with production

### ISSUE THREAD

**Issue by ArcanErasmus** [kitten-science/kitten-scientists#192]
### Version Check

- [X] I have updated to `v2.0.0-beta.7` or later.
- [ ] I have updated to the `nightly` build from last night (or latest one available).
- [ ] I have tested with the latest source code from `main` as of today.

### What browser are you using?

Firefox, desktop, windows 10

### How are you loading Kitten Scientists?

Userscript Manager (Tampermonkey)

### Describe the Bug

Every tick of KS, a single "sacrifice unicorns" press is enacted, sacrificing 2500 unicorns. However, I produce unicorns far faster than this, so effectively my tears production is capped by KS's speed, regardless of actual unicorn production.

### Your Savegame

[Kittens Game.txt](https://github.com/kitten-science/kitten-scientists/files/11023264/Kittens.Game.txt)

### Screenshots

![image](https://user-images.githubusercontent.com/8963206/226471389-e669a184-5f58-4dbd-a572-f924af12bc1d.png)
Sacrifice Unicorns is enabled, threshold is at 1M

![image](https://user-images.githubusercontent.com/8963206/226471408-1a99b8e5-33f2-436d-92bf-4436064e1c8c.png)
Wow, that's a lot of log messages (if only I could disable sacrifice messages...)!

![image](https://user-images.githubusercontent.com/8963206/226471425-8157a43a-19e5-4308-a66d-b2457a65b8d5.png)
And the number of Unicorns continues to climb, despite KS's best efforts!

btw thank you for your hard work maintaining KS!

**Comment by oliversalzburg** [comment]
Partially an upstream issue: https://bitbucket.org/bloodrizer/kitten-game/pull-requests/1172

Still needs a more optimized solution in KS.
