### ISSUE TITLE
Fix Cryochambers doesn't respect Resource Control on Void

### ISSUE THREAD

**Issue by ArcanErasmus** [kitten-science/kitten-scientists#193]
### Version Check

- [X] I have updated to `v2.0.0-beta.7` or later.
- [ ] I have updated to the `nightly` build from last night (or latest one available).
- [ ] I have tested with the latest source code from `main` as of today.

### What browser are you using?

Firefox, desktop, windows 10

### How are you loading Kitten Scientists?

Userscript Manager (Tampermonkey)

### Describe the Bug

I have Resource Control enabled for Void, set stockpile to 750, yet KS has slapped that Fix Cryochambers button the moment it had 500 Void.

### Your Savegame

[Kittens Game.txt](https://github.com/kitten-science/kitten-scientists/files/11100827/Kittens.Game.txt)

I just disabled the resource control, but that was because I only realized the bug after I went to turn it off. I would set it up but I'm in a rush right now, apologies.

**Comment by oliversalzburg** [comment]
Fix tested and verified.
