### ISSUE TITLE
Reset Timeline Resource limits are not persistent

### ISSUE THREAD

**Issue by acmihal** [kitten-science/kitten-scientists#20]
In the Time Control -> Reset Timeline -> Resource Control tree, the resource limit checkboxes and stock fields are not persistent across resets. If I set a bunch of values here then reset the timeline, I'm left with only Starchart selected and the stock field is changed to 500. The other Reset Timeline conditions, such as Bonfire and Space, seem to be working correctly.

**Comment by oliversalzburg** [comment]
I wasn't able to test the fix yet, but the mistake in the code seemed fairly obvious. I hope it works :D

**Comment by acmihal** [comment]
Confirmed fixed on v2.0.0-alpha.10-live.
