### ISSUE TITLE
Start Missions deselected missions are launched anyway

### ISSUE THREAD

**Issue by acmihal** [kitten-science/kitten-scientists#21]
In the Space -> Start Missions tree, deselected options are launched anyway. It seems like these options are ignored and all missions are always launched.

**Comment by oliversalzburg** [comment]
Looking at the code, it's clear that these settings are completely ignored. I can also remember getting sidetracked into solving some settings-related issues and then never finishing this. I hope to get to it during the weekend. Thanks for the report!

**Comment by acmihal** [comment]
Confirmed fixed on v2.0.0-alpha.10-live.
