### ISSUE TITLE
Option to suspend buying of Huts until price reduction is bought

### ISSUE THREAD

**Issue by dododome01** [kitten-science/kitten-scientists#211]
### Describe the Feature

Toggle to not buy houses until a specific amount of price reductions is bought.
Could be a number input (1=Ironwood Huts,...,4=Eulidium Huts)

**Comment by oliversalzburg** [comment]
I don't think this would be a good extension to KS as it stands today. I've marked the issue as a potential Kitten Engineers candidate. Please check <https://kitten-science.com/engineers/> to see what that's about.
