### ISSUE TITLE
Trading Seasons not persistent across a reset

### ISSUE THREAD

**Issue by acmihal** [kitten-science/kitten-scientists#23]
If you adjust the seasons where trading is enabled for different animals, the settings are not persistent across a reset. Additionally, the log message when activating new seasons looks like it has a bug:

Enabled trading with Winter in the {1}
Enabled trading with Winter in the {1}
Enabled trading with Autumn in the {1}
Enabled trading with Winter in the {1}
Enabled trading with Summer in the {1}

In the season drop-downs, there are also reset, enable-all, and disable-all buttons. None of these seem to do anything.

I'm tuning my paragon auto-farming config to always trade with everyone in every season, because the speedup is more important than the season bonus.

**Comment by oliversalzburg** [comment]
Excellent find. Thanks

**Comment by oliversalzburg** [comment]
Reopened because the enable-all/disable-all wasn't investigated.
