### ISSUE TITLE
Make Time Skp take into account stored heat

### ISSUE THREAD

**Issue by ptarjan** [kitten-science/kitten-scientists#300]
### Version Check

- [x] I have updated to `v2.0.0-beta.7` or later.
- [ ] I have updated to the `nightly` build from last night (or latest one available).
- [ ] I have tested with the latest source code from `main` as of today.

### What browser are you using?

Chrome

### How are you loading Kitten Scientists?

None

### Describe the Bug

Can the "Time Skip" logic take into account how much stored heat you have and enable the automation on the Chrono Furnace, then turn off the automation to use fewer crystals? Semantically I would like to skip all the non-redmoon years and I can't seem to encode that, since in its current state the system will skip using x45 crystals, build up 500% heat and then automatically skip over the exact season I wanted to be in.

### Screenshots

<img width="459" alt="image" src="https://github.com/kitten-science/kitten-scientists/assets/40143/168607b6-159f-48f9-98b2-4cabb113ad2b">

**Comment by oliversalzburg** [comment]
Sorry for taking so long to respond.

I understand your idea, and I'm also aware that the time control mechanic isn't working well for a lot of users for several reasons. You can find other open issues on the tracker that also point out other flaws.

I _do_ want to aim for a solution that takes every wish into consideration, but I don't think I will have time to work on this in the short term.

**Comment by oliversalzburg** [comment]
Closing Kitten Engineer candidate tickets for the time being. See <https://kitten-science.com/engineers/> for details.

**Comment by oliversalzburg** [comment]
Was actually never solved by Kitten Engineers, but Active Heat Transfer.
