### ISSUE TITLE
Persistent URLs for script

### ISSUE THREAD

**Issue by normalvector** [kitten-science/kitten-scientists#390]
### Describe the Enhancement

In order to use KS we need to load the script by referring to the URL hosting it, which currently includes the entire version number  with addresses such as 'https://github.com/kitten-science/kitten-scientists/releases/download/v2.0.0-beta.7/kitten-scientists-2.0.0-beta.7.user.js'.

Having the version number there means that users either end up using old versions when new ones are released as their own scripts become stale, or their scripts break as the old versions disappear and the URL no longer resolves.

To address this I'd suggest having two URLs which always point to the current versions, such as  kittens-scientists-latest.user.js and kittens-scientists-stable.user.js which would always be up-to-date and wouldn't require users to change their scripts and not care about version numbers, while anyone who does care can keep working with the absolute version URLs as they currently do.

**Comment by oliversalzburg** [comment]
That is a valid concern, but I'm not sure how feasible it is with the current release system. However, there is an update notification feature already built into Kitten Scientists already. It just hasn't been fully activated yet: 

https://github.com/kitten-science/kitten-scientists/blob/1bb3ec0b9e425c819816281ccf7329b5a128b7d1/packages/kitten-scientists/source/UserScript.ts#L138-L159

We might see this fully activated in the next release.

That being said, I'll think about if we can make your suggestion work as well.

**Comment by oliversalzburg** [comment]
- Stable: https://ks.rm-rf.link/stable.js
- Nightly: https://ks.rm-rf.link/nightly.js
- Dev: https://ks.rm-rf.link/dev.js

I hope this works 😄
