### ISSUE TITLE
Kitten Scientists Loads too late to get savegame data

### ISSUE THREAD

**Issue by sargun** [kitten-science/kitten-scientists#435]
### Version Check

- [X] I have updated to `v2.0.0-beta.7` or later.
- [X] I have updated to the `nightly` build from last night (or latest one available).
- [ ] I have tested with the latest source code from `main` as of today.

### What browser are you using?

Chrome 120.0.6099.71 (Official Build) (arm64) 
Tampermonkey 5.0

### How are you loading Kitten Scientists?

Userscript Manager (Tampermonkey)

### Describe the Bug

On initialization, the savegame is not being loaded. It appears that `getDefaultInstance` is not called until after all of the managers in the kittens game are being loaded, so the save game manager for KS is never called.

What that roughly looks like in the log start time:

```
(stuff above)
game#load - Processing challenges ...
game.js?rev_=1291_1702359754640:2401 game#load - Processing stats ...
game.js?rev_=1291_1702359754640:2401 game#load - Processing void ...
game.js?rev_=1291_1702359754640:238 Loading server settings...
game.js?rev_=1291_1702359754640:4400 starting web worker...
userscript.html?name=Kitten-Scientists.user.js&id=e08e9e1b-a303-4594-9851-0e1c314060cb:54 👩‍🔬 Kitten Scientists v2.0.0-beta.8-dev-af2ead2 constructed.
userscript.html?name=Kitten-Scientists.user.js&id=e08e9e1b-a303-4594-9851-0e1c314060cb:54 👩‍🔬 You are on the 'dev' release channel.
userscript.html?name=Kitten-Scientists.user.js&id=e08e9e1b-a303-4594-9851-0e1c314060cb:54 👩‍🔬 Selecting language 'en'.
userscript.html?name=Kitten-Scientists.user.js&id=e08e9e1b-a303-4594-9851-0e1c314060cb:54 👩‍🔬 Installing save game manager...
(stuff below)
```

I'm not sure what changed to make save game state load later. I can imagine two solutions:
1. Manually try to extract the last save by calling game.save(), and seeing if ks exists there
2. Figure out why KS is loading later.

### To Reproduce

1. Save game
2. Restart game (refresh page)
3. See state is not there.

**Comment by oliversalzburg** [comment]
Hmmm TM 5.0 just came out recently. I will have to investigate what's happening here. Thanks a lot for reporting!

**Comment by sargun** [comment]
Dumb question, why don't we (KS) just store our save / state in a parallel part of local storage, rather than injecting it into the saved state from kittens?

**Comment by oliversalzburg** [comment]
> Dumb question, why don't we (KS) just store our save / state in a parallel part of local storage, rather than injecting it into the saved state from kittens?

To allow the settings to sync to KGnet.

**Comment by oliversalzburg** [comment]
The order of log messages, as you provided them, is as expected. If you enable verbose logging in DevTools, you should see earlier events from KS as well. These would be very interesting to see what's happening under the hood. So far, I cannot reproduce this even with TM5.

**Comment by sargun** [comment]
So, it seems to be difficult to reproduce. I relaunched Chrome, and it stopped happening for a while. Then it started happening again...another relaunch later, it fixed itself. Looking at the code, it looks like the restore / startup process races with the game. Is there a better way to do it?

**Comment by oliversalzburg** [comment]
As long as there's only a single report of an issue that cannot be reproduced, there is nothing to be done.

**Comment by oliversalzburg** [comment]
Could you get the full verbose logs for when the issue happens? Maybe it at least gives some hints towards the root cause.
