### ISSUE TITLE
Improve UI layout - 4th "column" for KS options

### ISSUE THREAD

**Issue by WrayOfSunshine** [kitten-science/kitten-scientists#493]
### Describe the Feature

Currently, the KS options are a big block that interrupts space where the log would normally show. My proposal is that (perhaps optionally?) you instead shift all of the vanilla UI to the left and put the KS options in another column to the right of the logs.

**Comment by oliversalzburg** [comment]
The only reason for the current location is historical. It's just been like this since the very earliest version. So, we could definitely try some stuff :)

**Comment by oliversalzburg** [comment]
This was actually now implemented in:
- #545
