### ISSUE TITLE
Workshop upgrades not researched while ressources are available (in high production save)

### ISSUE THREAD

**Issue by Cirthy** [kitten-science/kitten-scientists#613]
### Version Check

- [X] I have updated to `v2.0.0-beta.8` or later.
- [ ] I have updated to the `nightly` build from last night (or latest one available).
- [ ] I have tested with the latest source code from `main` as of today.

### What browser are you using?

Chrome

### How are you loading Kitten Scientists?

Userscript Manager (Tampermonkey)

### Describe the Bug

Workshop upgrades are not researched whereas the ressources to do so are available. In the case of the save file I provide, the Ironwood upgrades is not researched. If I move kittensgame in the foreground and interact with it a bit, the upgrade eventually gets researched.

I've had similar issues with workshop upgrades. Sometimes at each KS cycle the ressources are allocated for crafting rather than upgrades (not a bug, but maybe it would be better to change the priority order for ressource allocation as upgrades appear more relevant than crafting most of the time). Sometimes the ressources are fully available but the upgrades is still not researched.

Anyhow, thanks a lot for developping KS!

### Your Savegame

Save file: [save_bug_report.txt](https://github.com/user-attachments/files/16688130/save_bug_report.txt)
KS settings: [ks_settings_bug_report.txt](https://github.com/user-attachments/files/16688129/ks_settings_bug_report.txt)

**Comment by oliversalzburg** [comment]
That certainly is one of the worst cases I've seen of KS not having its priorities straight :smile: I'm working on related issues in #591 and I hope the next release will have a better approach to also solve your problem.

Thanks for the report + save! That helps a lot :heart:

**Comment by oliversalzburg** [comment]
I evaluated this again with the latest nightly build. The Workshop now has distinct triggers for crafts and upgrades.

So, for the given save game, if you increase the main workshop trigger to 1%, and leave the upgrade unlock at 0%, upgrades will be unlocked as expected.

So I'm closing this ticket without adjusting the core logic here, in favor of user configuration options, and future work in optimizing purchases.
