### ISSUE TITLE
religion's opinion changed and be Different from User Documents

### ISSUE THREAD

**Issue by c940949574** [kitten-science/kitten-scientists#627]
### Describe the Enhancement

the range of Adore the Galaxy and Paradise of the Sun Now is be in the range of 0 to Infinity (-1).
How is it work now?It should be clearly described
![QQ_1725353750994](https://github.com/user-attachments/assets/d93ee776-4cd6-41eb-b5bc-f8cc55051b0b)

**Comment by oliversalzburg** [comment]
We have existing documentation about this at: https://kitten-science.com/sections/religion/#adore-the-galaxy

I understand that it is not explaining the behavior sufficiently. Thank you for the report :heart:

**Comment by c940949574** [comment]
> We have existing documentation about this at: https://kitten-science.com/sections/religion/#adore-the-galaxy
> 
> I understand that it is not explaining the behavior sufficiently. Thank you for the report ❤️

The range of this value in the document is a floating point number from 0 to 1, but now it is 0 to infinity. 
If i set it as 0.75 that it automatically changes to 0.
version nightly v2.0.0-beta.9-20240902-fe79f2d.
![affa20fc-7032-4c01-8112-52be0d1cd5eb](https://github.com/user-attachments/assets/951daa50-f3f7-4007-8e8a-1b4ac24fa752)

**Comment by c940949574** [comment]
> We have existing documentation about this at: https://kitten-science.com/sections/religion/#adore-the-galaxy
> 
> I understand that it is not explaining the behavior sufficiently. Thank you for the report ❤️

Version of v2.0.0 beta 8, it works like kitten science's document. But the other version doesn't work that way.
That is an bug or a feature update? I dont know.
![image](https://github.com/user-attachments/assets/e32d86c2-8906-44d7-8090-7962b7d1c952)

**Comment by oliversalzburg** [comment]
For my own reference, this is likely a regression from normalization at https://github.com/kitten-science/kitten-scientists/blob/c18a9025ff9d53328b842196b9411db45b032729/packages/kitten-scientists/source/ui/ReligionSettingsUi.ts#L149

**Comment by oliversalzburg** [comment]
This report hints at a larger issue, that has been annoying me for a long time. If a setting has a `trigger`, it can either by a value between `0` and `1`, or it can be an integer of any size. There is currently no way to tell in the code which _kind_ of trigger is desired.

Thus, I will take the opportunity to refactor out this problem once and for all.
