### ISSUE TITLE
Enhancement: In "Time Control" make seasons a submenu of each CYCLE instead of overall

### ISSUE THREAD

**Issue by petethered** [kitten-science/kitten-scientists#82]
### Describe the Enhancement

<img width="310" alt="image" src="https://user-images.githubusercontent.com/1239247/209445831-9c0b9cc1-6cf2-4748-97d8-a4987931337f.png">

The problem comes from the fact that temporal paradox only occurs on season change, not when you shatter a crystal to skip forward a year.  If you are trying to build void via paradox, you are stuck with either:

Spending all 5 years in a cycle 

or

Spending a season in EVERY cycle 

If the seasons are moved to being sub options of particular cycles, then you can spend X seasons in selected cycles and still timeskip reasonably quickly.

----

[Kittens Game - Run 18 - Year 3670 - Spring, day 44.txt](https://github.com/kitten-science/kitten-scientists/files/10298965/Kittens.Game.-.Run.18.-.Year.3670.-.Spring.day.44.txt)

In the example game above, I would love to:

Skip all cycles EXCEPT Redmoon, but only spend one season per year inside the redmoon cycle to lower my paradox timer (spending 5 seasons total in the cycle) and trigger it so I can build flux without having the spend all 20 seasons inside the redmoon cycle.

### Your Savegame

```Text
Too big, pasted link above.
```

**Comment by petethered** [comment]
You have the UI sketched out for this kind of seasonal selection 

<img width="353" alt="image" src="https://user-images.githubusercontent.com/1239247/209446121-77873ce3-9341-43de-82f3-9ffeac74a085.png">

In the trade menu that would accelerate implentation of this enhancement.

**Comment by oliversalzburg** [comment]
There's a couple open feature requests about time control right now. We have to be careful that the system doesn't become too difficult to control. It's clear that we need better ways to manage time skipping though. Ideally, we can cover this use case as well.

**Comment by petethered** [comment]
Yeah... i had other requests related to time control but it would get kinda crazy to interface out 

But i figured since trading already had season selection UI it wouldn't be too unusual to see

**Comment by oliversalzburg** [comment]
Yeah, I'm not sure if this season selection is the right UI approach going forward, given the amount of individual toggles to control the overall configuration. I'm thinking maybe we need something that looks more like a calendar, so you can more easily map out the "time zones" you want to be in.

**Comment by petethered** [comment]
Yeah...

What might be a better option is something like:

<img width="210" alt="image" src="https://user-images.githubusercontent.com/1239247/209695551-a34d6e77-74dd-425e-b42b-be92d6ac95f3.png">

WHere it it says "Skip All Seasons" (default on) and you still have the 4 season selector below.

That's kinda a happy medium.

Currently you can:

1. Skip all seasons
2. Spend all 4 seasons in a cycle (if that cycle is disabled)
3. Spend 1,2,3,4 seasons in all cycles (depending on which season is selected)

If you add a "Skip All Seasons" (or ignore season) it would add a option to "spend 1,2,3, or 4 seasons only in these cycles"

This would fill most use cases (wanting to spend some time in redmoon during the early stage for unobtainum, or time in charon to build hash levels, or a season in Tminus for the storage) and let you build up void.

**Comment by oliversalzburg** [comment]
Relates to #190

**Comment by oliversalzburg** [comment]
By now I can definitely say that I understand this issue. I've had long play tests where I realized for the first time that my excessive time acceleration configuration was preventing me from earning any void.

That being said, I don't think this season-based granular control is really the answer. At the core, this enhancement should allow for a better balance between time acceleration and earning void. KS is historically very bad at balancing things.

I feel like we want to really weigh season _changes_ against year skips and/or time acceleration. Maybe the solution can be reduced to something as simple as that.

I'll give it more thought and see what I can come up with.

**Comment by petethered** [comment]
Well... my memory is a bit dusty as I ["beat the game"](https://www.reddit.com/r/kittensgame/comments/13ovs7a/is_there_a_relic_limit_somewhere_north_of_1e301/)  a while back.

The season change is where the void kicks in, so you could add a "Wait for season change" subcheck under each of the cycles in the time change menu and have it skip after the first season change.

Or go the other way as "Skip ASAP" so it's checked by default and 2 checks means instant skip, one check means wait for season change.

**Comment by oliversalzburg** [comment]
Thank you for contributing feedback on this old issue and congrats for reaching these insane levels :)

I'm actually wondering if we really still need this, after getting the "Active Heat Transfer" feature. I sadly don't really fully understand it yet, but it really helps with this aspect. It takes pretty long for me to have all the heat go down, so there are plenty season changes before KS time skips again.

**Comment by petethered** [comment]
I ran a grease monkey script on top of KS during play.

Because the "optimal" solution changes depending on your place in the progression timeline, I had many versions those scripts and it looks like I didn't keep them.

What  do remember was that I untoggled the skip in charon/redmoon in KS and my script would basically check if was summer and if heat was ok, time skip 1 (or 5 years later in the run) letting KS take over.

When I shifted to more then 5 year skips, I believe I set it to (number of cycles - 1)*5 so that each time it burned a full cycle it would move backwards one cycle every big skip so i'd hit every cycle in case I wanted to stay.

----

In writing that, you could probably just get away with a "Wait until summer" checkbox for the skip in a particular cycle.  That might be the most understandable way of putting a one season stay in the KS interface.

**Comment by oliversalzburg** [comment]
After looking into this even more, I'm more convinced that this is already, should be covered by the active heat transfer. In any case, the time control options need to be thought of in combination.

I remember, I was hoping to make big strides in the time control section of KS until beta 9, but I couldn't really reach any higher levels of consolidation, that I was hoping for. The "Active Heat Transfer", which was contributed by someone else, seems to be one of the biggest enhancements in this area for a long time.

Working on all the paragon farming features during this beta cycle allowed me to go to 250k paragon myself now though :smile: So I'm really hoping to flesh out the late game and end game features _now_.
