### ISSUE TITLE
Time Control Manager - Make Tempus Fugit obey resource control

### ISSUE THREAD

**Issue by petethered** [kitten-science/kitten-scientists#83]
### Describe the Enhancement

The accelerateTime function in TimeControlManager does not 

1. Follow the limits set by Resource Control
2. Stop itself 

Here's a rewritten version of the function that will do so:

```
  accelerateTime() {
    // we can assume they want to accelerate time as the check is in the tick

    // how much flux is available
    const temporalFluxAvailable = this._workshopManager.getValueAvailable("temporalFlux")
    
    // if there's no available flux (we went below the limit) 
    if (temporalFluxAvailable === 0) {
      // if accelerated
      if (this._host.gamePage.time.isAccelerated === true) {
        // stop the acceleration
        this._host.gamePage.time.isAccelerated = false;
      }
      return;
    }

    // get the flux so we know the max
    const temporalFlux = this._host.gamePage.resPool.get("temporalFlux");

    // get the max that I can use
    const maxUsable = temporalFlux.maxValue - this._workshopManager.getStock("temporalFlux");

    // calculate the percentage of the available to use flux vs the max
    const percentageAvailable = temporalFluxAvailable / maxUsable;

    // if available percentage is >= the trigger value
    if (percentageAvailable >= this.settings.accelerateTime.trigger) {
      // accelerate only if needed so it doesn't pollute the logs
      if (this._host.gamePage.time.isAccelerated === false) {
        this._host.gamePage.time.isAccelerated = true;
        this._host.engine.iactivity("act.accelerate", [], "ks-accelerate");
        this._host.engine.storeForSummary("accelerate", 1);      
      }
    }
  }
```

Here's a standalone console version for testing

```
  let accelerateTime = () => {
    // we can assume they wany to accelerate time as the check is in the tick

    // how much flux is available
    const temporalFluxAvailable = kittenScientists.engine.workshopManager.getValueAvailable("temporalFlux")
    console.log("Available: " + temporalFluxAvailable);

        
    // if there's no available flux (we went below the limit) 
    if (temporalFluxAvailable === 0) {
      // if accelerated
      if (gamePage.time.isAccelerated) {
        // stop the acceleration
        gamePage.time.isAccelerated = false;
        console.log("Stopped since no available and running")
      }
      return;
    }

    // get the flux so we know the max
    const temporalFlux = gamePage.resPool.get("temporalFlux");

    // get the max that I can use
    const maxUsable = temporalFlux.maxValue - kittenScientists.engine.workshopManager.getStock("temporalFlux");
    console.log("Max Usable: " + maxUsable);

    // calculate the percentage of the available to use flux vs the max
    const percentageAvailable = temporalFluxAvailable / maxUsable;
    console.log("percentage of max: " + percentageAvailable);

    // if available percentage is >= the trigger value
    if (percentageAvailable >= kittenScientists.engine.timeControlManager.settings.accelerateTime.trigger) {
      // accelerate only if needed so it doesn't pollute the logs
      if (gamePage.time.isAccelerated === false) {
        console.log("Accelerating");
        gamePage.time.isAccelerated = true;
        kittenScientists.engine.iactivity("act.accelerate", [], "ks-accelerate");
        kittenScientists.engine.storeForSummary("accelerate", 1);      
      } else {
        console.log("Already accelerated");
      }
    }
  }

if (typeof(timeTest) !== "undefined") {
clearInterval(timeTest);
}
var timeTest = "";
var timeTest = setInterval(function() { accelerateTime() }, 500);

```

Save file:

[Kittens Game - Run 18 - Year 13091 - Spring, day 49.txt](https://github.com/kitten-science/kitten-scientists/files/10304633/Kittens.Game.-.Run.18.-.Year.13091.-.Spring.day.49.txt)

### Your Savegame

```Text
Too big, uploaded above
```

**Comment by oliversalzburg** [comment]
Sounds about right. Should definitely have this fixed.

btw, what's the problem with the savegame text box in the report form? I assume pasting the contents doesn't work, but can't you attach the savegame file in that box? Not that it really matters, just wondering.

**Comment by petethered** [comment]
Re: Save game 

There's a 64k character limit and my save file is 73 KB

It's NOT a WYSIWYG box so you can't drag and drop in the file and have it upload.

Maybe it's because of the placeholder? The save game textarea is the only one on the three different submit types that isn't WYSIWYG

**Comment by oliversalzburg** [comment]
Thanks for the info. I will try to replicate that myself and fix the report form. :+1:

**Comment by oliversalzburg** [comment]
I've only implemented part of your solution for now. While I think it has merit to evaluate the trigger in relation to only the _available_ resources, the behavior of triggers in the remaining script is to apply to the entire capacity. I'm not sure if I'd want to change that, but whatever approach we use should be applied as consistently as possible. Such a large change would require a dedicated ticket for consideration.

**Comment by petethered** [comment]
Out of curiosity, what other consumable has a trigger in the UI, and can be resource controlled that consumes everything?


Timeskip trigger will stop time skipping if it goes below the resource control (RC).

Workshop triggers at a percentage of max as set but doesn't consume past the RC even if your max is set to infinity.

I'm not sure about hunters, so maybe there?

Trade triggers at percentage and won't go below the RC (tested using leviathans and unobtainium)

---

Religion will go below the RC, but I'm pretty sure that there's no way to only partially "praise the sun", so it's immaterial.

---

That leaves tempus fugit/flux consumption.

**Comment by oliversalzburg** [comment]
> Out of curiosity, what other consumable has a trigger in the UI, and can be resource controlled that consumes everything?
I'm not sure. Answering this would likely require reviewing every single trigger and I'm sure that would likely just surface more cases of inconsistency :D

I believe the trade trigger applies to catpower, gold, and traded resource actually. I'm not sure if it really preserves all three.
