### ISSUE TITLE
Gather catnip

### ISSUE THREAD

**Issue by oliversalzburg** [kitten-science/kitten-scientists#86]
### Describe the Feature

KS should be able to automatically gather catnip, if you're in a state of the game where this is applicable.

**Comment by dethmourne** [comment]
FWIW Script Kitties handled this with the following function, which was then called as part of a core "check everything to see what we need to do next" loop:

```
function autoNip() {
	if (gamePage.bld.buildingsData[0].val < 30) {
		$(".btnContent:contains('Gather')").trigger("click");

		// Set the triggerImmediate flag for this function, so that it is called again next tick
		dispatchFunctions.autoNip.triggerImmediate = true;
	}
}
```

Obviously the implementation in kitten-scientists will vary somewhat, but hopefully that helps for anyone who is taking this on.
