### ISSUE TITLE
Blackcoin Trading Thresholds

### ISSUE THREAD

**Issue by acmihal** [kitten-science/kitten-scientists#99]
### Describe the Enhancement

The current code has hardcoded trading thresholds at < 950 to buy, and > 1050 to sell. Furthermore, there is a waitForBestPrice condition set at < 860 which I think is meant to detect a market implosions, but is set too low to detect implosions that land in the range [860.0, 880.022). WaitForBestPrice is also not persistent across browser tab reloads - it gets initialized back to false.

I propose that the waitForBestPrice condition be removed entirely, and that the buy/sell targets be made user-settable. I think you could probably use buy=1090 and sell=1095 by default? I think this should provide sufficient hysteresis.

**Comment by acmihal** [comment]
Also there is a settings.tradeBlackcoin.trigger which sets the minimum number of relics before pressing the buy button. It is set to 10k but there is no control in the UI to change it.

**Comment by oliversalzburg** [comment]
Yeah, this seems like the right way to go.

> Also there is a settings.tradeBlackcoin.trigger which sets the minimum number of relics before pressing the buy button. It is set to 10k but there is no control in the UI to change it.

This should have been fixed in
- #81

**Comment by petethered** [comment]
Funny... I was about to raise this issue myself.

You can gap the buy/sell tighter.  Something like below 1090 buy, above 1091 sell.

This will prevent the minor price fluctuations from causing it to buy/sell/loop on ticks.
